polypheny/Polypheny-UI

- src/app/components/graph/graph.component.ts
- src/app/components/right-sidebar/right-sidebar.component.html
- src/app/components/right-sidebar/right-sidebar.component.scss
- src/app/components/right-sidebar/right-sidebar.component.ts
- src/app/services/config.service.ts
- src/app/services/information.service.ts
- src/app/services/webui-settings.service.ts
- src/app/views/forms/form-generator/form-generator.component.ts
- src/index.html
- src/scss/_variables.scss
The connection urls are built from the ports coming from the server (or existing settings in the localStorage) and from location.hostname
> Build connection url from hostname and port

- src/app/views/querying/graphical-querying/graphical-querying.component.html
- src/app/views/querying/graphical-querying/graphical-querying.component.scss
Tested on chrome, firefox and ie11
> fixes #67 for firefox and ie11

- src/app/views/forms/form-generator/form-generator.component.html
- src/app/views/forms/form-generator/form-generator.component.scss
- src/app/views/forms/form-generator/form-generator.component.ts
- src/app/views/querying/relational-algebra/relational-algebra.component.ts
(polypheny-db/Polypheny-DB#226)
> UI support for ConfigClazzes

- src/app/components/graph/graph.component.html
- src/app/components/graph/graph.component.ts
- src/app/containers/default-layout/default-layout.component.html
- src/app/services/crud.service.ts
- src/app/views/query-interfaces/query-interfaces.component.html
- src/app/views/query-interfaces/query-interfaces.component.scss
- src/app/views/query-interfaces/query-interfaces.component.ts
- src/app/views/query-interfaces/query-interfaces.model.ts
- src/app/views/querying/sql-console/sql-console.component.ts
- src/app/views/stores/stores.component.html
- src/app/views/views-routing.module.ts
- src/app/views/views.module.ts
See polypheny/Polypheny-DB#268
> Query interface manager

- package-lock.json
- src/app/components/components.module.ts
- src/app/components/data-view/data-card/data-card.component.html
- src/app/components/data-view/data-carousel/data-carousel.component.html
- src/app/components/data-view/data-table/data-table.component.html
- src/app/components/data-view/data-table/data-table.component.scss
- src/app/components/data-view/data-table/data-table.component.ts
- src/app/components/data-view/expandable-text/expandable-text.component.html
- src/app/components/data-view/expandable-text/expandable-text.component.scss
- src/app/components/data-view/expandable-text/expandable-text.component.ts
- src/app/components/data-view/models/result-set.model.ts
- src/app/components/toast/toast.component.html
- src/app/components/toast/toast.component.scss
- src/app/components/toast/toast.component.ts
- src/app/components/toast/toast.model.ts
- src/app/components/toast/toast.service.ts
- src/app/services/crud.service.ts
- src/app/services/util.service.ts
- src/app/views/adapters/adapters.component.html
- src/app/views/adapters/adapters.component.ts
- src/app/views/forms/form-generator/form-generator.component.ts
- src/app/views/hub/hub.component.ts
- src/app/views/query-interfaces/query-interfaces.component.ts
- src/app/views/querying/relational-algebra/relational-algebra.component.ts
- src/app/views/querying/sql-console/sql-console.component.html
- src/app/views/querying/sql-console/sql-console.component.ts
- src/app/views/schema-editing/edit-columns/edit-columns.component.ts
- src/app/views/schema-editing/edit-tables/edit-tables.component.html
- src/app/views/schema-editing/edit-tables/edit-tables.component.ts
- src/app/views/uml/uml.component.ts
- Refactoring the result model
- Copy generated queries by clicking on the toast header
- Expandable text in data views
> Refactor Result model

- src/app/components/breadcrumb/breadcrumb.service.ts
- src/app/components/data-view/data-table/data-table.component.html
- src/app/components/data-view/data-table/data-table.component.scss
- src/app/components/data-view/data-table/data-table.component.ts
- src/app/components/data-view/data-view.component.ts
- src/app/components/data-view/input/input.component.html
- src/app/components/data-view/input/input.component.scss
- src/app/components/data-view/input/input.component.ts
- src/app/components/data-view/models/result-set.model.ts
- src/app/components/data-view/models/sort-state.model.ts
- src/app/pipes/pipes.ts
- src/app/services/crud.service.ts
- src/app/services/dbms-types.service.ts
- src/app/views/querying/sql-console/sql-console.component.html
- src/app/views/querying/sql-console/sql-console.component.scss
- src/app/views/querying/sql-console/sql-console.component.ts
- src/app/views/schema-editing/edit-columns/edit-columns.component.html
- src/app/views/schema-editing/edit-columns/edit-columns.component.scss
- src/app/views/schema-editing/edit-columns/edit-columns.component.ts
- src/app/views/schema-editing/edit-source-columns/edit-source-columns.component.scss
- src/app/views/uml/uml.component.html
- src/app/views/uml/uml.component.ts
- src/app/views/uml/uml.model.ts
- src/app/views/views.module.ts
- UI for horizontal partitioning
- Updates to fk options in UML view
- Polished displaying of executed query in result view
- Advanced input validation for data view
- improved behavior of schema management view
- Add progress bar for file downloads
- Remove sort option for some types
> Horizontal Partitioning

- src/app/views/schema-editing/edit-columns/edit-columns.component.html
- Remove ability to drop primary key from list of constraints
> DDL Manager

- src/app/components/data-view/models/result-set.model.ts
- src/app/views/schema-editing/edit-columns/edit-columns.component.html
- src/app/views/schema-editing/edit-columns/edit-columns.component.ts
> Fixes for horizontal partitioning

- package-lock.json
- src/app/components/toast/toast.component.scss
- src/app/views/adapters/adapters.component.ts
Better feedback when updating AdapterSettings
> Query-a-File-System security

- src/app/views/forms/form-generator/form-generator.component.html
- src/app/views/forms/form-generator/form-generator.component.scss
Remove the save settings buttons in "group card header" and create a new one at the top right corner. Fixes polypheny/Polypheny-DB#175.
> Only one save settings button

- src/app/views/querying/explore-by-example/explore-by-example.component.ts
- src/app/views/querying/graphical-querying/graphical-querying.component.ts
- src/app/views/schema-editing/edit-columns/edit-columns.component.html
- src/app/views/schema-editing/edit-columns/edit-columns.component.ts
- src/app/views/schema-editing/edit-source-columns/edit-source-columns.component.html
- src/app/views/schema-editing/edit-source-columns/edit-source-columns.component.ts
- src/app/views/uml/uml.component.ts
- src/app/views/uml/uml.model.ts
Added a table containing foreign key information in both edit-column view and edit-source-column view.
Has to be merged after PR polypheny/Polypheny-DB#299 (File system data source) is merged in PolyphenyDB.
Fixes #125  -List foreign key constraints in schema view of PolyphenyDB
Table Image:-
> List foreign key constraints in schema view

- src/app/components/data-view/data-view.component.html
- src/app/components/data-view/models/result-set.model.ts
- src/app/views/querying/console/console.component.html
This PR adds CQL as a language option for the Polypheny console.
It is the visual counterpart for the PR [CQL Console](https://github.com/polypheny/Polypheny-DB/pull/367) of Polypheny-DB.
> CQL Console Integration

- src/app/components/data-view/input/input.component.html
- src/app/views/querying/console/console.component.html
This PR fixes two minor visual errors:
- Margin between console and buttons disapears, when history is empty
- Nullable Varchars miss the text in the data editor
> Console Margin and Varchar Null Bug

- src/app/components/data-view/data-card/data-card.component.html
- src/app/components/data-view/data-card/data-card.component.ts
- src/app/components/data-view/data-carousel/data-carousel.component.html
- src/app/components/data-view/data-table/data-table.component.html
- src/app/components/data-view/data-view.component.ts
- src/app/services/dbms-types.service.ts
- src/app/views/querying/console/console.component.html
This PR enables the PolyPig language, which is a adjusted version of [Apache Pig](https://pig.apache.org/), for the console.
_This PR relies on [PR #370](https://github.com/polypheny/Polypheny-DB/pull/370) of Polypheny-DB._
> Enable PolyPig Language

- src/app/components/data-view/data-table/data-table.component.html
- src/app/components/data-view/data-table/data-table.component.ts
- src/app/components/data-view/data-view.component.ts
- src/app/models/ui-request.model.ts
- src/app/services/crud.service.ts
- src/app/views/forms/form-generator/form-generator.component.html
- src/app/views/forms/form-generator/form-generator.component.scss
- src/app/views/forms/form-generator/form-generator.component.ts
- src/app/views/querying/graphical-querying/graphical-querying.component.ts
- src/app/views/querying/graphical-querying/refinement-options/refinement-options.component.ts
- src/app/views/querying/relational-algebra/relational-algebra.component.html
- src/app/views/querying/relational-algebra/relational-algebra.component.scss
- src/app/views/querying/relational-algebra/relational-algebra.component.ts
This PR prepares Polypheny-UI for its first release:
- shows if config needs restart to change config value
- now possible to analyze query in plan builder
- all config switches have the same color
- fixed focus in data search
> Prepare for release

- src/app/components/breadcrumb/breadcrumb.component.html
- src/app/components/breadcrumb/breadcrumb.service.ts
- src/app/components/data-view/models/result-set.model.ts
- src/app/services/crud.service.ts
- src/app/views/adapters/adapters.component.html
- src/app/views/monitoring/monitoring.component.ts
- src/app/views/querying/console/console.component.html
- src/app/views/schema-editing/edit-source-columns/edit-source-columns.component.html
- src/app/views/schema-editing/edit-source-columns/edit-source-columns.component.ts
- src/app/views/schema-editing/edit-tables/edit-tables.component.ts
- src/app/views/schema-editing/schema-editing.component.ts
- src/app/views/schema-editing/statistics-column/statistics-column.component.html
- src/app/views/schema-editing/statistics-column/statistics-column.component.ts
This PR fixes the directory path for CSV sources. 
Additionally, it persists the Toast messages when switching to the console and adds missing placement checks to remove errors in the editing tab, as well as actively blocks empty name changes.
> CSV Directory Fix

- src/app/views/dashboard/dashboard.component.html
- src/app/views/dashboard/dashboard.component.ts
This PR improves the dashboard.
If the dashboard information is not yet ready, this is displayed and the system tries to reload the information for 2 minutes.
> Dashboard improvement

- src/app/components/left-sidebar/left-sidebar.component.html
- src/app/components/left-sidebar/left-sidebar.component.ts
Fixes polypheny/Polypheny-DB#296
> SideBar fix #296

- src/app/views/adapters/adapters.component.html
- src/app/views/querying/console/console.component.ts
- fixes reset of namespace in advanced console
- improved client-side logic to handle switching of namespace in longer scripts
> Fix to correctly set and persist namespace in the console

- src/app/models/catalog.model.ts
- src/app/views/adapters/adapter.model.ts
- src/app/views/adapters/adapters.component.ts
These are the required UI changes for [#498](https://github.com/polypheny/Polypheny-DB/pull/498).
> Simplify Adapter serialization

- src/app/components/components.module.ts
- src/app/components/data-view/data-view.component.ts
- src/app/components/data-view/input/input.component.html
- src/app/components/data-view/models/result-set.model.ts
- src/app/models/ui-request.model.ts
- src/app/plugins/notebooks/components/edit-notebook/edit-notebook.component.html
- src/app/plugins/notebooks/components/edit-notebook/edit-notebook.component.ts
- src/app/plugins/notebooks/components/edit-notebook/nb-cell/nb-cell.component.html
- src/app/plugins/notebooks/components/edit-notebook/nb-cell/nb-cell.component.ts
- src/app/plugins/notebooks/components/notebooks-dashboard/notebooks-dashboard.component.html
- src/app/plugins/notebooks/components/notebooks-dashboard/notebooks-dashboard.component.ts
- src/app/plugins/notebooks/notebooks.module.ts
- src/app/plugins/notebooks/services/notebooks-content.service.ts
- src/app/plugins/notebooks/services/notebooks.service.ts
- src/app/services/crud.service.ts
- src/app/views/dockerconfig/dockerconfig.component.ts
- src/app/views/forms/form-generator/form-generator.component.ts
- src/app/views/query-interfaces/query-interfaces.component.html
- src/app/views/query-interfaces/query-interfaces.component.ts
- src/app/views/query-interfaces/query-interfaces.model.ts
- src/app/views/schema-editing/schema-editing.component.ts
This PR belongs to the PR [#502](https://github.com/polypheny/Polypheny-DB/pull/502).
This PR introduces a new visual for boolean values in the Data view.
Further it resolves problems with correctly parsing und display queries and notebook related features.
Additionally, it fixes various inconsistencies and bugs with other components.
> Fixes for Boolean Values, Materialized View, Toast Messages, Notebooks

- src/app/views/schema-editing/edit-columns/edit-columns.component.html
- Fix display of nullable checkbox
- Set the correct option in collection type drop down
- Hide the nullable checkbox for primary keys
> Improve column editing
